Cargo.toml, appveyor.yml, src/error.rs, src/lib.rs, src/stage1.rs
Make sure we don't crash on empty inputs (or any other random data up to 8k)
=> no crash on empty input

Cargo.toml, simd-fuzz-target/src/main.rs, src/lib.rs, src/numberparse.rs, src/value.rs, src/value/borrowed.rs, src/value/borrowed/serialize.rs, src/value/generator.rs, src/value/owned.rs, src/value/owned/serialize.rs, tests/jsonchecker.rs
* Add a custom serializer for simd-json's Value types based on the code generator from https://github.com/maciejhirsz/json-rust 
* Improve float parsing
=> Bserialize

src/value/borrowed.rs, src/value/owned.rs
Pull out the owned and borrowed deserializer.
=> Re-factor out different deserialisers

README.md
=> codecov badge?

.github/workflows/validate.yaml, src/error.rs, src/numberparse.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs
Add tests for code that isn't properly covered.
=> More tests

src/value/borrowed.rs, src/value/borrowed/cmp.rs, src/value/owned.rs, src/value/owned/cmp.rs
We lost the capability to compare &'s in the last cleanup lets add it back in a nicer way
=> Allow comparing refs

src/value/borrowed.rs
This is mostly API convenience, it exposes two functions for the borrowed value:
1) `into_static` which consumes a borrowed value `Value<'value>` and returns it as `Value<'static>`
2) `clone_static` which clones or copies a value `&Value<'value>` and returns the clone as `Value<'static>`
Both effectively help to strip lifetimes for situations where they are burdensome to deal with.
=> Add function to turn a borrowed value into 'static

.github/workflows/rust.yml, .github/workflows/validate.yaml, Cargo.toml, README.md, src/known_key.rs, src/lib.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs
Adding a feature for accessing known keys faster.
=> Adding KnownKey

src/value/borrowed.rs, src/value/borrowed/from.rs, src/value/owned.rs, src/value/owned/from.rs
Add From<Object> for values for convenience (trivial change)
=> Add ::from for Object

src/avx2/deser.rs, src/avx2/stage1.rs, src/avx2/utf8check.rs, src/neon/deser.rs, src/neon/stage1.rs, src/neon/utf8check.rs, src/sse42/stage1.rs, src/sse42/utf8check.rs
* This replaces #46
* If this looks good, we can merge to 0.2 and I'll put together another PR to track a reasonable upstream release (which will take care of #62)!
=> feat: improve arch-specific code similarity

src/avx2/stage1.rs, src/avx2/utf8check.rs, src/lib.rs, src/neon/deser.rs, src/neon/stage1.rs, src/neon/utf8check.rs, src/sse42/stage1.rs, src/sse42/utf8check.rs
DONE:
* extract SimdInput struct
* create Stage1Parse trait
TODO:
* apply same technique to utf8check
* run copious benchmarks to make sure we didn't regress
=> Arch alignment

README.md, src/avx2/stage1.rs, src/avx2/utf8check.rs, src/lib.rs, src/neon/stage1.rs, src/neon/utf8check.rs, src/sse42/stage1.rs, src/sse42/utf8check.rs, src/utf8check.rs
* improve Utf8 modularity w/ trait
* align [sse42, avx2, neon] to upstream version(s) 0.2.1
TODO:
* benchmark to ensure no adverse effects
=> feat: improve utf8 modularity w/ Utf8Check trait

.github/workflows/tests.yml, Cargo.toml
=> Use alloc counter on stable

src/error.rs, src/lib.rs, src/serde.rs, src/serde/value/borrowed.rs, src/serde/value/owned.rs, src/value.rs, src/value/borrowed.rs, src/value/borrowed/serialize.rs, src/value/owned.rs, src/value/owned/serialize.rs
#101 brought this up, we're missing the from_reader method, so here it is.
=> Add from_reader method for serde integration

Cargo.toml, README.md, src/lib.rs, src/serde.rs, src/serde/value/owned/se.rs
closes #114
Closing this will imply also renaming the repository to `simd-json`
=> Rename repo to simd-json

src/serde.rs, src/serde/de.rs
=> Add serde enum deserializer

src/lib.rs, src/serde.rs, src/serde/de.rs, src/serde/value/borrowed/de.rs, src/serde/value/owned/de.rs
=> Array as struct

src/lib.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs
closes https://github.com/simd-lite/simd-json/issues/151
=> Ability to reuse Deserializers to avoid allocations

src/known_key.rs, src/serde/se.rs, src/serde/se/pp.rs, src/serde/value/borrowed/de.rs, src/serde/value/borrowed/se.rs, src/value/borrowed.rs, src/value/borrowed/cmp.rs, src/value/borrowed/from.rs, src/value/borrowed/serialize.rs, src/value/owned.rs, src/value/owned/from.rs, src/value/owned/serialize.rs
=> Rename lifetime name

Cargo.toml, src/avx2/stage1.rs, src/avx2/utf8check.rs, src/lib.rs, src/sse42/stage1.rs, src/sse42/utf8check.rs, src/utf8check.rs
closes https://github.com/simd-lite/simd-json/issues/98
=> Sync utf8 validation with upstream (lookup4)

src/value/borrowed.rs, src/value/borrowed/cmp.rs, src/value/owned.rs, src/value/owned/cmp.rs, src/value/tape.rs
=> Add PartialEq<&[T]> and PartialEq<HashMap<_,_>> implementations to Value

src/lib.rs
=> Expose tape from Deserializer

Cargo.toml, src/numberparse.rs, src/prelude.rs, src/serde.rs, src/value/borrowed.rs, src/value/owned.rs
=> Update value trait

src/macros.rs, src/serde/value.rs, src/serde/value/borrowed.rs, src/serde/value/borrowed/se.rs, src/value/owned.rs
Signed-off-by: Darach Ennis <darach@gmail.com>
=> Add json_typed macros for borrowed json literal support

src/serde/se.rs
Spams console output - maybe left over from an old PR.
=> Remove unnecessary dbg call

src/serde/se.rs
Previously, serializing a struct like this:
```rust
#[derive(Debug, Serialize)]
struct Foo {
#[serde(flatten)]
bar: HashMap<u32, bool>,
}
```
would produce incorrect output (a single opening curly brace) when the HashMap is empty. This is due to incorrect logic surrounding calls to `serialize_map` with an unknown length, which occurs when using the flatten feature. This PR fixes this bug.
=> Fix incorrect output when serializing unknown length zero-length maps

src/serde/se.rs
Previously, serializing a struct like:
```rust
#[derive(Clone, Debug, PartialEq, serde::Serialize)]
struct Foo {
pub bar: HashMap<i32, i32>,
}
```
would result in incorrect JSON output (no quotes around the keys). This PR adds a MapKeySerializer that corrects this behavior by wrapping numeric keys in quotes to more closely match the behavior of serde_json, and also adds a test case.
=> Fix serialization of numeric map keys

src/known_key.rs, src/value.rs
Reverts simd-lite/simd-json#187 - we were over here and somehow the CI didn't catch that it doesn't even compile :(
cc @mfelsche can you make a new PR with this improvements when you get a chance
=> Revert "Add KnownKey::map* methods for lookups on Value::Objects inner maps."

.github/workflows/nightly.yml, .github/workflows/tests.yml
See https://github.com/rust-lang/rustup/issues/2759
=> Use rustup beta, which fixes the spurious OOM issue on Windows 

src/known_key.rs
This is fixing the stupid mistakes in #187 
I hope is CI is having a closer look
=> Fix variable error and doctests in known_key module

.github/workflows/nightly.yml, .github/workflows/quality.yaml, .github/workflows/tests.yml, src/serde/value/borrowed/de.rs, src/serde/value/owned/de.rs, src/sse42/stage1.rs
Fix issues with deserializing enums
=> Enum deserializer

src/lib.rs
fix typo for function in lib.rs
=> fix: ✏️ fix typo

Cargo.toml, src/avx2/stage1.rs, src/lib.rs, src/neon/deser.rs, src/neon/stage1.rs, src/numberparse.rs, src/sse42/stage1.rs, src/stage2.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs, tests/serde_128_bit.rs
Work in progress for rust 1.59 on arm/m1
=> First stab at rust 1.59 on arm

.gitignore, src/stage2.rs
remove set_len and get_unchecked_mut from stage2, fixes #226
=> Remove initial set_len in stage2

.github/workflows/quality.yaml
Signed-off-by: Heinz N. Gies <heinz@licenser.net>
=> Move to llvm cov and codecov

src/lib.rs
Heya @scrabsha I've to reverts simd-lite/simd-json#232 for now as now all the doc tests fail :(m sorry
=> Revert "Improve the error message emitted when a SIMD-incompatible CPU is used"

benches/parse.rs
This is needed in order to execute the benchmarks. They were based in the previous version of criterion.
=> Fix bench file for criterion v0.4.0

src/avx2/deser.rs, src/error.rs, src/lib.rs, src/neon/deser.rs, src/numberparse/approx.rs, src/numberparse/correct.rs, src/serde.rs, src/serde/de.rs, src/serde/value/borrowed/de.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/de.rs, src/serde/value/owned/se.rs, src/serde/value/shared.rs, src/simd128/deser.rs, src/sse42/deser.rs, src/stage2.rs, src/value/borrowed.rs, src/value/owned.rs
cleanup serializer and deserializer implementations
=> Variant access tests and cleanup

src/numberparse/approx.rs, src/numberparse/correct.rs, src/stage2.rs
improve slice access to use .get_kindof_unchecked
=> improve access patterns

Cargo.toml, src/lib.rs
fix #291, hopefully, can't create the error locally but this should hopefully work.
=> Hopefully fix docs rs builds

Cargo.toml, src/known_key.rs, src/lib.rs, src/macros.rs, src/serde/se/pp.rs, src/serde/value/borrowed/de.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/de.rs, src/serde/value/owned/se.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs
@ritchie46 want to take a look and see if / how this works for you?
=> Move to ahesh for known keys as suggested in #290

.github/workflows/tests.yml, Cargo.toml, src/lib.rs, src/numberparse.rs, src/numberparse/correct.rs, src/simd128/deser.rs
=> Fix issues

.github/workflows/tests.yml, Cargo.toml
hopefully fix the need for getrandom
=> Clean up wasm dependencies

benches/parse.rs, data/hdfs_log.json, src/lib.rs, src/value/borrowed.rs, src/value/owned.rs
structural_indexes allocations can be saved in some scenarios
=> reuse structural_indexes

README.md
fixed some minor misspelled words in the readme file.
=> Fixed Minor Typos in README.md

Cargo.toml, fuzz/Cargo.toml, fuzz/fuzz_targets/failing.rs, fuzz/fuzz_targets/passing.rs, fuzz/fuzz_targets/real.rs, src/error.rs, src/impls/native/deser.rs, src/known_key.rs, src/lib.rs, src/macros.rs, src/prelude.rs, src/serde.rs, src/serde/value/borrowed/de.rs, src/serde/value/owned/de.rs, src/stage2.rs, src/stringparse.rs, src/tests.rs, src/tests/serde.rs, src/value.rs, src/value/borrowed.rs, src/value/borrowed/serialize.rs, src/value/owned.rs, src/value/owned/serialize.rs, src/value/tape.rs, src/value/tape/array.rs, src/value/tape/cmp.rs, src/value/tape/object.rs, src/value/tape/trait_impls.rs, tests/alloc.rs, tests/jsonchecker.rs
Add dom style access to `Tape`
=> Tape value

.github/workflows/pr-perf.yml, .github/workflows/tests.yml, Cargo.toml, benches/to_tape.rs, src/error.rs, src/known_key.rs, src/lib.rs, src/safer_unchecked.rs, src/serde/de.rs, src/serde/se.rs, src/serde/se/pp.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/se.rs, src/serde/value/shared.rs, src/stage2.rs, src/tests/impls.rs, src/value/borrowed.rs, src/value/borrowed/cmp.rs, src/value/borrowed/from.rs, src/value/borrowed/serialize.rs, src/value/owned.rs, src/value/owned/cmp.rs, src/value/owned/from.rs, src/value/owned/serialize.rs, src/value/tape.rs, src/value/tape/cmp.rs, src/value/tape/trait_impls.rs, tests/alloc.rs
Working on some performance improvements.
=> Perf improvements

README.md
Fixed #352 
Added Contribution section.
@Licenser  check and merge the PR. Thank You!
=> Fixed: added contribution section to  README.md

src/impls/native/stage1.rs, src/impls/neon/stage1.rs
Fixes: https://github.com/simd-lite/simd-json/issues/361
=> Fix ptr write alignment

Cargo.toml, src/numberparse/correct.rs
=> remove lexical-core dependency

Cargo.toml, README.md, src/cow.rs, src/lib.rs, src/macros.rs, src/prelude.rs, src/value.rs, src/value/borrowed.rs, src/value/lazy.rs, src/value/owned.rs
I noticed various things in the docs that could be improved, feel free to cherry-pick the changes you like.
Both README.md and the lib.rs documentation were missing features the other had. 
I've merged the two and updated where necessary, and made it so that lib.rs includes the README.md content.
I've also made various small fixes in various places.
=> Improve and update the documentation

Cargo.toml
=> Remove wasm/getramdom
