simd-lite/simd-json

src/lib.rs
This reverts commit 0ff4ecec0aaf822f650e704e4ed67c2b6a01a6c6.
This fixes a seg-fault that was introduced with 0.1.14. The reason for that segfault is that it introduced an issue of us reading after the input data od possibly crossing page boundaries.
Better handling of relocated data might solve that but rust could get into the way here. Worth an investigation later.
=> Revert "Optimize string parsing"

src/lib.rs, src/serde/de.rs, src/stage2.rs, src/value/borrowed.rs, src/value/owned.rs
This improvs string parsing. We can get around quite a bit of checks that way:
* also it is not relocate strings that do not include escaped characters
* we do not need to differentiate between long and short strings
* we don't need to count string length any more
=> Str parse2

README.md
Since we don't have an appveyor.xml anymore...?
=> chore: remove appveyor badge

.github/workflows/validate.yaml, Cargo.toml, src/avx2/deser.rs, src/avx2/stage1.rs, src/error.rs, src/known_key.rs, src/lib.rs, src/macros.rs, src/neon/deser.rs, src/numberparse.rs, src/serde.rs, src/serde/de.rs, src/serde/value/borrowed/de.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/de.rs, src/serde/value/owned/se.rs, src/sse42/deser.rs, src/stage2.rs, src/value.rs, src/value/borrowed.rs, src/value/borrowed/cmp.rs, src/value/borrowed/from.rs, src/value/borrowed/serialize.rs, src/value/owned.rs, src/value/owned/cmp.rs, src/value/owned/from.rs, src/value/owned/serialize.rs, src/value/tape.rs
We can move some of the parsing logic into stage 2 instead of checking them after that. This simplifies the code for parse() .
Performance wise it looks like a small improvement too.
```
======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         450 MB/s   490 MB/s   630 MB/s   350 MB/s
data/citm_catalog.json  1170 MB/s   600 MB/s  1450 MB/s   760 MB/s
data/twitter.json        950 MB/s   700 MB/s   950 MB/s   750 MB/s
data/log.json           1080 MB/s  2170 MB/s  1080 MB/s  1080 MB/s
```
```
======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         460 MB/s   490 MB/s   630 MB/s   350 MB/s
data/citm_catalog.json  1120 MB/s   600 MB/s  1450 MB/s   770 MB/s
data/twitter.json        960 MB/s   700 MB/s   970 MB/s   750 …
```
=> Move more parsing in stage2

README.md
The lack of the 'https://' prefix results in 'serde.rs'
being interpreted as a link to a file in the repository.
So, add the 'https://' to correctly link to the website.
=> README: properly link to serde website

src/lib.rs, src/serde/de.rs, src/stage2.rs, src/value/borrowed.rs, src/value/owned.rs, src/value/tape.rs
Storing the end node allow skipping entire nested note if we need to while looking over it.
bench to be done
=> Encode object end for nested tape nodes

src/avx2/deser.rs, src/avx2/generator.rs, src/avx2/stage1.rs, src/known_key.rs, src/lib.rs, src/neon/deser.rs, src/neon/generator.rs, src/neon/stage1.rs, src/numberparse.rs, src/serde/de.rs, src/serde/value/owned/se.rs, src/sse42/deser.rs, src/sse42/generator.rs, src/sse42/stage1.rs, src/stage2.rs, src/value.rs, src/value/borrowed.rs, src/value/borrowed/cmp.rs, src/value/borrowed/from.rs, src/value/borrowed/serialize.rs, src/value/generator.rs, src/value/owned.rs, src/value/owned/cmp.rs, src/value/owned/from.rs, src/value/owned/serialize.rs
This is a pure API change and should have no performance impact. The goal here is to split out different aspects for the value trait to allow implementing only parts of it. Since 0.2 is a declared breaking API it feels like the right time to do.
This will allow us to do things like make non mutable Value variants that have better performance or even serialise directly to objects.
=> Split traits into read, mutate and build

.github/workflows/quality.yaml, .github/workflows/tests.yml, README.md, tests/alloc.rs
simple test fixes to deal with inconsistencies. The inconsistency are likely based on an additional allocation to be introduced when we're too close to a page boundary.
=> Compare <= for alloc tests

Cargo.toml, README.md, src/lib.rs
#101 shows that allowing fallback is a tricky beast. It leads to users having a bad experience, that shouldn't happen while not compiling is annoying having a slow system for non-obvious reason from a library that is about speed is worse. 
This PR disables it and creates an error when compiled w/o see42, avx2 or NEON.  It can be re-enabled with the `allow-non-simd` flag.
solves #34
=> Switch to not compiling with a non SIMD capable cpu settings

src/known_key.rs
Add KnownKey.key() for when lookup() is insufficient ( presence vs nullity)
=> Add KnownKey.key() for when lookup() is insufficient ( presence vs nullity)

Cargo.toml, benches/parse.rs, examples/perf.rs
The benches now include simd_json::to_tape, drop the C++ FFI crate
because it's not on cargo and anyway out of date, and use thinLTO
to be more representative.
This reduces the dependencies needed for cargo test from 133
to 85 by putting benchmarking-only dependencies behind a feature.
It's ~30% faster to compile.
=> Fixup benchmarks and dependencies

src/serde/se.rs
Hi there, sorry for this second PR. :flushed: 
I oversaw another `dbg!()` in the other PR which was also there. The last PR was really just copy-from-stacktrace-and-remove-in-fork, but this is according to the search the last call to the debug macro left in the codebase. Maybe I should've looked a bit closer before submitting that one.
=> Remove another dbg macro call

src/serde/value/borrowed/se.rs, src/serde/value/owned/se.rs
Previously, calling `simd_json::serde::to_{owned,borrowed}_value` on a struct like this:
```rust
#[derive(Clone, Debug, PartialEq, serde::Serialize)]
struct Foo {
pub bar: HashMap<i32, i32>,
}
```
would result in an error. This PR makes BorrowedValue and OwnedValue more closely behave like `serde_json::Value` by also accepting numeric map keys.
=> Allow Value to accept numeric map keys as serialization target

src/known_key.rs, src/value.rs
This is handy if you already know you have a `Value::Object(map)` in your hands, in which case we can spare a match on the enum variant.
This is a backport of what we did in https://github.com/tremor-rs/tremor-runtime/pull/969
=> Add KnownKey::map* methods for lookups on Value::Objects inner maps.

src/neon/stage1.rs
simd-json still cannot build on aarch64 with nightly Rust despite https://github.com/rust-lang/stdarch/pull/1157 being fixed because the stdarch submodule in Rust has not been bumped yet.
Using a locally compiled Rust with bumped stdarch it compiles and runs the tests with the changes in this pull request. This just removes some dead code left over from the simdutf8 refactoring to make clippy happy.
Benchmarks on a MacBook Air:
```
group                                         base
-----                                         ----
apache_builds/simd_json::to_borrowed_value    1.00    179.3±0.98µs   676.8 MB/sec
apache_builds/simd_json::to_owned_value       1.00    491.1±5.14µs   247.2 MB/sec
apache_builds/simd_json::to_tape              1.00     58.4±0.65µs     2.0 GB/sec …
```
=> aarch64: remove unused UTF-8 remnants causing build failures

Cargo.toml, README.md, src/lib.rs
Preventing the library from producing invalid code on some machines (See #200)
=> Made the compatiblity check fail on absense of the `pclmulqdq`-feature

.github/workflows/nightly.yml, .github/workflows/quality.yaml, .github/workflows/tests.yml, Cargo.toml, README.md, src/lib.rs, src/sse42/stage1.rs
I was unable to create a faster function with SIMD instructions, primarily because x86 has no 64-bit vector multiply instruction. 
On my machine, the fallback function makes the parsing ~10% slower
Fixes #202
=> Added fallback function for CPUs that don't support pclmulqdq instructions

.cargo/config, Cargo.toml, Makefile, src/lib.rs, src/neon/stage1.rs, src/numberparse.rs, src/serde/se.rs, src/serde/se/pp.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/se.rs, src/simd128/deser.rs, src/simd128/mod.rs, src/simd128/stage1.rs, src/value/borrowed.rs, src/value/owned.rs, tests/jsonchecker.rs
This adds support for two targets: 
1) `wasm32-unknown-unknown` - the current go to for running Rust on web browsers. The standard library is incredibly limited here and running tests is difficult.
2) `wasm32-wasi` - currently most useful for running tests, but may become more desirable in the future due to powerful sandboxing features offered by wasm runtimes on server.
In theory, any future wasm32 targets will be supported without any modification - e.g. `wasm32-web`. I've not made any effort to support `wasm64` yet, though enabling this in the future should be a simple matter of changing some cfg macros.
Some key changes and issues:
- proptest is incompatible with wasm targets as it relies on being able to fork, which is not possible. As a result, this dev dependency has to be gated …
=> feat(arch): add support for wasm32 with simd128 feature

src/lib.rs
`simd-json` should be compiled on SIMD-compatible CPUs only. As such, it's a
good idea to ensure at compilation that the CPU is indeed compatible.
The previous check was performed thanks to a bunch of `#[cfg(...)]`
conditionals which would expand to incorrect code or not, hence raising a
compile error or not.
The error message was the following:
```
$ cargo c
Checking simd-json v0.5.1 (/home/ssha/git/simd-json)
error[E0308]: mismatched types
--> src/lib.rs:221:86
|
221 | fn please_compile_with_a_simd_compatible_cpu_setting_read_the_simdjsonrs_readme() -> ! {}
|    ----------------------------------------------------------------------------      ^ expected `!`, found `()`
|    |
|    implicitly returns `()` as its body has no tail or `return` expression
|
= note:   expected type `!`
found …
```
=> Improve the error message emitted when a SIMD-incompatible CPU is used

src/avx2/deser.rs, src/charutils.rs, src/lib.rs, src/neon/deser.rs, src/numberparse.rs, src/safer_unchecked.rs, src/simd128/deser.rs, src/sse42/deser.rs, src/stage2.rs, src/stringparse.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs
This is HEAVY wip because these bounds check panic in ~~*every single test*~~ 95 tests. Indexing out of bounds is UB, which means this crate has no test that isn't currently UB :)
There's standard library checks for this too (if you run with `-Zbuild-std`), but those will just SIGILL your program, and you have to use gdb to get a backtrace.
So I copied this from where I added this in https://github.com/iximeow/yaxpeax-x86/blob/no-gods-no-/src/safer_unchecked.rs.
I'll leave this as draft while I investigate what's up and then mark it as ready once I get stuck on some of these.
=> Add bounds checked get_unchecked, use it everywhere.

.github/workflows/tests.yml, Cargo.toml, README.md, src/lib.rs, src/macros.rs, src/numberparse/correct.rs, src/serde/value/borrowed/de.rs, src/serde/value/owned/de.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs, src/value/tape.rs
Add a feature flag for strict (non UB) parsing of duplicate keys in objects for Value structs.
=> Add value-no-dup-keys flag

.cargo/config, src/lib.rs
Before:
```
error[E0308]: mismatched types
--> (**masked**)/src/lib.rs:228:86
|
228 | fn please_compile_with_a_simd_compatible_cpu_setting_read_the_simdjsonrs_readme() -> ! {}
|    ----------------------------------------------------------------------------      ^ expected `!`, found `()`
|    |
|    implicitly returns `()` as its body has no tail or `return` expression
|
= note:   expected type `!`
found unit type `()`
For more information about this error, try `rustc --explain E0308`.
error: could not compile `simd-json` due to previous error
```
After:
```
error: Please compile with a simd compatible cpu setting, read the simdjson README.
--> (**masked**)/src/lib.rs:229:5
|
229 |     compile_error!("Please compile with a simd compatible cpu setting, read the simdjson README.");
| …
```
=> Improve error message for non-SIMD scenarios

src/lib.rs
We don't need to set the entire alligned buffer to 0, instead a single 0 is enough to mark that we terminate the json string
=> Fix setting too much of the alligned buffer to 0

src/neon/stage1.rs
alternative implementation taken from https://github.com/simdjson/simdjson/blob/master/include/simdjson/arm64/bitmask.h
I wonder if it would be better to just have the version of simdjson since it is stated that it is more powerful than pmull?
Closes #293
=> Fix neon implementation for cpu without feat_pmull

src/lib.rs
It is UB to create `Vec` with unitialized bytes. 
This fixes that by ensuring we only `set_len` to the length we have written.
Adding a few `dbg!` statements showing the `len` and `capacity` whilst reading this [file](https://gist.githubusercontent.com/getorca/d3a6460f0d14b573c1d38322828d34d8/raw/20a934b9671c99d96f14461521493abf4d08ae31/test.jsonl) showed they where off. 
```
[/home/ritchie46/Downloads/simd-json/src/lib.rs:492] len = 1432
[/home/ritchie46/Downloads/simd-json/src/lib.rs:492] input_buffer.capacity = 1496
[/home/ritchie46/Downloads/simd-json/src/lib.rs:492] len = 1431
[/home/ritchie46/Downloads/simd-json/src/lib.rs:492] input_buffer.capacity = 1495
```
Reading that file in valgrind also showed that we read the uninitialized bytes confirming UB.
Valgrind output:
``` …
```
=> fix: initialize bytes up to `len` of `AlignedBuf`.

.github/workflows/nightly.yml, src/avx2/deser.rs, src/lib.rs, src/neon/deser.rs, src/simd128/deser.rs, src/sse42/deser.rs, src/stage2.rs
Switch to using pointers for `input` in string parsing to avoid fighting the borrow checker and tripping up the optimizer in nightly.
=> Use pointers instead of slices to avoid tripping the optimizer in nightly

Cargo.toml
Right now, local builds of the docs for simd-json fail due to the "target-cpu" compilation error. This unfortunately also happens on docs.rs, although one would it expect it doesn't. This fixes it by changing the `cfg(docsrs)` to `cfg(doc)`, which should apply both to local doc builds as well as when publishing to docs.rs.
=> Fix docs build

src/lib.rs, src/serde/de.rs, src/stage2.rs, src/value.rs, src/value/borrowed.rs, src/value/owned.rs, src/value/tape.rs
The two parameters in Object and Array are undocumented and not
understood without looking at the source code.
Refactor to be more explanatory and add docs
I'm not sure of the usefulness of `end`. It's not used currently and maybe can be removed?
=> refactor tape::Node<'input>

src/impls/avx2/stage1.rs, src/impls/native/deser.rs, src/impls/native/stage1.rs, src/impls/neon/stage1.rs, src/impls/portable/stage1.rs, src/impls/simd128/deser.rs, src/impls/simd128/stage1.rs, src/impls/sse42/deser.rs, src/impls/sse42/stage1.rs, src/known_key.rs, src/lib.rs, src/serde.rs
This pull request fixes typos in explanation comments of source files. I kindly request the repository maintainers to review and merge it. Thanks! :heart:
=> fix typos in explanation text in source files

src/impls/neon/deser.rs, src/impls/neon/stage1.rs, src/lib.rs, src/tests/impls.rs
Various recent refactors have left the project unbuildable on aarch64.
CI seems to be stuck for this arch, so there's been no recent signal
that things are broken. This is currently affecting the 0.13.0 release.
Test Plan:
```
$ cargo build --all --target aarch64-apple-darwin
$ cargo test --target aarch64-apple-darwin
$ cargo build --all --target x86_64-apple-darwin
$ cargo test --target x86_64-apple-darwin
```
=> Fix aarch64 build

src/macros.rs
(This is a relatively small change, hence no prior discussion in an issue)
This PR adapts the technique [outlined in `hashbrown`](https://github.com/rust-lang/hashbrown/pull/209) for branch hints on stable, utilizing the `#[cold]` attribute.  
In my local benchmarks I observed an improvement of ~8-13% on average (but I'm not quite sure how many of these were flukes).
=> Better stable branch hints

Cargo.toml, README.md, src/numberparse/correct.rs, tests/jsonchecker.rs
Currently simd-json errors when a to large integer overflows while parsing.
This PR adds a feature flag `big-int-as-float` that handles cases when int overflows and interprets that as a float instead.
The downside is that you loose some precision but that's ok if you opt into it and how it currently works in most JavaScript based engines.
For example:
`JSON.parse("999999999999999999999999999999")` in Chrome (v8) returns 1e+30
=> Treat big ints as floats via feature flag "big-int-as-float"

src/lib.rs, src/numberparse.rs, src/stringparse.rs
This pull request fixes the issue where the `simd-json` fallback code path isn't working for unsupported CPU architectures.
`#[allow(dead_code)]` is added for the `handle_unicode_codepoint` function since this function is not used when building the fallback logic.
An alternative method would be changing the `Cargo.toml` file to gate `runtime-detection` feature behind `x86_64` and `x86` architectures.
=> Fix compatibility on unsupported CPU architectures

src/error.rs
These fields can be useful when trying to inspect the error.
=> Expose the fields of `Error` as public

Cargo.toml, src/impls/avx2/deser.rs, src/impls/avx2/stage1.rs, src/lib.rs, src/serde.rs, src/serde/se.rs, src/serde/se/pp.rs, src/serde/value/borrowed/de.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/de.rs, src/serde/value/owned/se.rs, src/value/tape/cmp.rs
Compiling for the `i686-unknown-linux-gnu` target leads to multiple compilation failures.
The first set was easy to solve (akin to #246). The second issue is that `std::arch::x86_64::_mm_cvtsi128_si64` does not seem to have an equivalent for `std::arch::x86`. I think this is an oversight in `std::arch::x86`?
I am not confident enough in my SIMD knowledge to create a clever workaround, so I copied the "native rust implementation" for `x86`. If there is some workaround without using `_mm_cvtsi128_si64`, then feel free to change it.
> [!NOTE]
> I do not have a `x86` system myself, so I could not test the changes locally. I only checked by running `cargo build --target i686-unknown-linux-gnu`
=> Fix x86 compilation

src/numberparse/correct.rs, src/serde.rs, src/serde/de.rs, src/serde/de/tests.rs
We falsly returned i64 for non negative numbers that were in the i64 range; fixes #383
=> Fix int parsing

Cargo.toml, src/value/tape.rs
Signed-off-by: Heinz N. Gies <heinz@licenser.net>
=> Add deserialize method to tape

src/lib.rs
I was trying to find `simd_json::to_borrowed_value()` and got pretty lost, because it's not there on the front page of the docs, and searching for it first turns up `simd_json::serde::to_borrowed_value()`, which isn't the same thing.
Using `doc(inline)` makes it show up with its correct name in the crate root docs:
Current:
=> Add doc(inline) on glob reexport

src/error.rs
(Again a "make simd_json drop more easily into a serde_json context") these methods on Error _roughly_ classify the error in the same way as their namesakes on `serde_json::Error`.
Cargo clippy, fmt, and test all run.
=> Serde json error classification

src/error.rs, src/lib.rs, src/value/tape.rs
This is kind of a prereq for any RawValue-like capability. 
As ever, 'my' use case requires the Deserialize to "introspect" or "peek at" the JSON, possibly multiple times, in order to "try" possibly multiple different "sub deserializations" for an Enum. With `serde_json::RawValue`, you have access to the string slice that backs the value, so the code tries that string as various different types (enabled by features). 
Because `simd_json` doesn't seem to keep the string around (and, anyway, it's a mutated bytes buf), the alternative is to introspect the Node vector held by the deserializer. Hence `as_value`. 
Additionally, reusing the Deserializer - which multiple attempted deserializations would require - won't work without some sort of "start again" operation since a deserialization …
=> Deserializer as Value and restartable

README.md
Miri has been disabled since August 2023 (https://github.com/simd-lite/simd-json/commit/a03d8f979e095b36ee1a16ff280e21a6ef4b9933) with no obvious movement to re-enable testing. Removing it as a tagline feature will help to remove any uncertainty or bad feelings about this project unintentionally lying about miri UB testing.
=> Remove line about being tested with Miri

src/numberparse/correct.rs
This is a questionable feature in Rust lexer and `simd-json` is the only known crate on crates.io that is using it. It's not being removed *yet*, but it would still be better to avoid using it.
See https://github.com/rust-lang/rust/pull/137394 and linked issues for more details.
=> Remove a starting underscore in floating point exponent

src/lib.rs, src/serde/se.rs, src/tests.rs, src/tests/impls.rs, src/tests/serde.rs
Address serialization issues with empty enums to ensure correct output for various enum variants. Introduce tests to validate the serialization behavior.
=> Fix empty enum serialization

src/serde.rs
Document the behavior of `from_reader`, highlighting that it reads the entire input into memory before parsing. This change addresses potential performance concerns and clarifies that it does not support streaming. Suggest using `from_slice` for better memory management.
Fixes #417
=> Add warning for from_reader to improve documentation

src/impls/avx2/deser.rs, src/impls/avx2/stage1.rs, src/impls/native/stage1.rs, src/impls/neon/stage1.rs, src/impls/portable/stage1.rs, src/impls/sse42/stage1.rs, src/lib.rs, src/macros.rs, src/numberparse/approx.rs, src/numberparse/correct.rs, src/serde.rs, src/serde/de.rs, src/serde/se/pp.rs, src/serde/value/borrowed/se.rs, src/serde/value/owned/se.rs, src/stage2.rs
Refactor the code to enhance organization by utilizing macros for static casts. This change simplifies import statements and improves overall code clarity.
=> Refactor imports to use macros for static casts and improve code organization

.github/workflows/quality.yaml, .github/workflows/tests.yml, Cargo.toml, examples/perf.rs, src/error.rs, src/impls/avx2/deser.rs, src/impls/native/stage1.rs, src/impls/sse42/deser.rs, src/lib.rs, src/macros.rs, src/numberparse/approx.rs, src/serde.rs, src/value/borrowed.rs
Allow lints for "unnecessary transmutes" for now.
=> examples/perf: Add an arch flag to run only on x86_64
